spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.108/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  # 返回前端不显示null的内容
  jackson:
    default-property-inclusion: non_null
#  redis:
#    host: 127.0.0.1
#    port: 6379
server:
  context-path: /sell
